# Generated by Django 5.1.2 on 2024-10-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='answer_choices',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
