# Generated by Django 5.1.2 on 2024-10-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_text_question_answer_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
