# Generated by Django 5.1.2 on 2024-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_quizresult_college_email_quizresult_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="usn",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
