# Generated by Django 5.1.2 on 2024-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_quizresult_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
