# Generated by Django 5.1.2 on 2024-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_quizresult_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='attempted_questions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='correct_answers',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='incorrect_answers',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
