# Generated by Django 5.1.2 on 2024-10-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_quizresult_attempted_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='attempted_questions',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='incorrect_answers',
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myapp.quizresult')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.answer')),
            ],
        ),
    ]
